### ISSUE TITLE
Use atmega128 and ENC28J60

### ISSUE THREAD

**Issue by gitronik** [per1234/Ariadne-Bootloader#25]
if i will use for atmega128 and ENC28J60, it can suported?

**Comment by per1234** [comment]
It should be possible to port the bootloader to ATmega128 fairly easily. I don't have any plans to do this in the near future. If you do it and submit a pull request I will eventually merge it but I currently don't have time for working on this project.

Adding ENC28J60 support would be very difficult if it's even possible. If there is ever any progress on that it will be noted in this issue:
https://github.com/loathingKernel/ariadne-bootloader/issues/4
You can subscribe to it.
